language: c

compiler:
  - gcc

install:
  - source ./scripts/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - source ./scripts/ptex-ng.sh
  - source ./scripts/local.sh
  - source ./scripts/run.sh
  - cd ../test
  - ptex-ng --format=platex-ng --shell-escape test
