install:
  - source ./support/texlive.sh

addons:
  artifacts:
    debug: true

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - fc-cache -rv /tmp/texlive/texmf-dist/fonts/opentype
  - fc-cache -rv /tmp/texlive/texmf-dist/fonts/truetype
  - cd source
  - xetex fduthesis.ins
  - cd ../test
  - xelatex  -interaction=nonstopmode test
  - lualatex -interaction=nonstopmode test
