install:
  - source ./scripts/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - source ./scripts/local.sh
  - source ./scripts/run.sh
  - texlua build.lua check
  - cat ./build/test/02-basic.luatex.diff
  # - texlua build.lua check -f -e pdftex 03-logo

notifications:
  email:
    - pssysrq@163.com
