install:
  - source ./support/texlive.sh

addons:
  artifacts:
    debug: true

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - cp -r /tmp/texlive/texmf-dist/fonts/opentype /usr/local/share/fonts
  - cp -r /tmp/texlive/texmf-dist/fonts/truetype /usr/local/share/fonts
  - fc-cache -rv
  - fc-list
#  - cd source
#  - xetex fduthesis.ins
#  - cd ../test
#  - xelatex  -interaction=nonstopmode test
#  - lualatex -interaction=nonstopmode test
