install:
  - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  # - source ./support/local.sh
  # - source ./support/run.sh
  - cd source
  - xetex fduthesis.dtx
  - cp fduthesis.cls      ../test/fduthesis.cls
  - cp fduthesis-en.cls   ../test/fduthesis-en.cls
  - cp fduthesis.def      ../test/fduthesis.def
  - cp fduthesis-user.def ../test/fduthesis-user.def
  - cd ../logo
  - xelatex  -interaction=nonstopmode fudan-name
  - cd ../test
  - xelatex  -interaction=nonstopmode test
  - cat test.log
