language: c

compiler:
  - gcc

install:
  - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - source ./support/ptex-ng.sh
  - source ./support/local.sh
  - source ./support/run.sh
  - cd ../logo
  - pdflatex -interaction=nonstopmode -shell-escape fdulogo-example
  - pdflatex -interaction=nonstopmode               fduthesis-cover
  - mkdir pdf
  - mv fudan-*.pdf pdf
  - cd ../test
  - aptex --format=aplatex --shell-escape test
