install:
  - source ./scripts/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - source ./scripts/local.sh
  - source ./scripts/run.sh
  - texlua build.lua check
  - texlua build.lua check --quiet --force --engine pdftex "03-logo"

after_failure:
  - cat ./build/test/*.diff

notifications:
  email:
    - pssysrq@163.com
