install:
  - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - source ./support/local.sh
  - source ./support/run.sh
  - cd ../logo
  - pdflatex -interaction=nonstopmode -shell-escape fdulogo-example
  - pdflatex -interaction=nonstopmode               fduthesis-cover
  - mkdir pdf
  - mv fudan-*.pdf pdf
  - cd ../test
  - xelatex  -interaction=nonstopmode test
  - xelatex  -interaction=nonstopmode test
  - xelatex  -interaction=nonstopmode test-en
  - xelatex  -interaction=nonstopmode test-en
  - source ../support/clean.sh
  - lualatex -interaction=nonstopmode test
  - lualatex -interaction=nonstopmode test
  - lualatex -interaction=nonstopmode test-en
  - lualatex -interaction=nonstopmode test-en
