install:
  - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - git clone https://github.com/Stone-Zeng/zhlipsum.git
  - mkdir -p /home/travis/texmf/tex/latex/zhlipsum
  - cp zhlipsum/zhlipsum.sty /home/travis/texmf/tex/latex/zhlipsum
  - cp zhlipsum/zhlipsum-zh-cn.def /home/travis/texmf/tex/latex/zhlipsum
  - texhash
  - cp -r /tmp/texlive/texmf-dist/fonts/opentype /home/travis/.fonts
  - fc-cache -rv
  - kpsewhich --var-value=TEXMFLOCAL
  - kpsewhich --var-value=TEXMFHOME
  - kpsewhich kantlipsum.sty
  - kpsewhich zhlipsum.sty
  
#  - cd source
#  - xetex fduthesis.ins
#  - cd ../test
#  - xelatex  -interaction=nonstopmode test
#  - lualatex -interaction=nonstopmode test
