install:
  - source ./scripts/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - source ./scripts/local.sh
  - source ./scripts/run.sh
  - texlua build.lua check
  - texlua build.lua check -f -e pdftex 03-logo
