install:
  - source ./scripts/texlive.sh
  - source ./scripts/local.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - source ./scripts/run.sh
  - pdflatex test

notifications:
  email:
    - pssysrq@163.com
