install:
  - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - fc-cache -rv
  - cd source
  - xetex fduthesis.ins
  - cd ../test
  - xelatex  -interaction=nonstopmode test
  - lualatex -interaction=nonstopmode test
