# Site settings
title: fduthesis
description: LaTeX thesis template for Fudan University
author: Xiangdong Zeng
email: xdzeng96@gmail.com
github_username:  stone-zeng
language: zh-Hans
timezone: Asia/Shanghai

# URL
url: ""
baseurl: /fduthesis

# Build settings
markdown: kramdown
theme: minima
permalink: :year-:month-:day-:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - tex/
